#!/bin/sh
c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy RemoteSigned -Command -File '.git\hooks\mass-usp-compiler.ps1 -series3 -path ../../src/RMC3/'

c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy RemoteSigned -Command -File '.git\hooks\mass-usp-compiler.ps1 -series3 -path ../../src/FT/'

c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy RemoteSigned -Command -File '.git\hooks\mass-usp-compiler.ps1 -series2 -path ../../src/TPCS/'
